client_max_body_size 50m;

location = /install.php          { deny all; return 403; }
location ^~ /install/            { deny all; return 403; }
location = /config.php           { deny all; return 403; }
location = /config_override.php  { deny all; return 403; }
location = /config_si.php        { deny all; return 403; }
location ^~ /custom/blowfish/    { deny all; return 403; }
location ^~ /upload/import/      { deny all; return 403; }
location ^~ /upload/tmp/         { deny all; return 403; }

location ^~ /upload/  { location ~* \.(php|phtml|phar|tpl|pl|cgi|log|sql|gz|zip|tar)$ { deny all; return 403; } }
location ^~ /cache/   { location ~* \.(php|phtml|phar|tpl|pl|cgi|log|sql|gz|zip|tar)$ { deny all; return 403; } }
location ^~ /custom/  { location ~* \.(php|phtml|phar|tpl|pl|cgi|log|sql|gz|zip|tar)$ { deny all; return 403; } }
location ^~ /modules/ { location ~* \.(php|phtml|phar|tpl|pl|cgi|log|sql|gz|zip|tar)$ { deny all; return 403; } }
location ^~ /data/    { location ~* \.(php|phtml|phar|tpl|pl|cgi|log|sql|gz|zip|tar)$ { deny all; return 403; } }
