tsd.core.authentication.enable = true
tsd.core.authentication.plugin = arena.ArenaAuthentication
tsd.core.plugin_path = /opt/opentsdb-plugin
tsd.core.auto_create_metrics = true
tsd.core.enable_api = true
tsd.core.enable_ui = true
tsd.mode = rw
tsd.storage.hbase.prefetch_meta = true
