location = /Api/access_token {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/Api/index.php;
    fastcgi_param SCRIPT_NAME /Api/index.php;
    fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    fastcgi_pass 127.0.0.1:9000;
}

location ^~ /Api/V8/ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/Api/index.php;
    fastcgi_param SCRIPT_NAME /Api/index.php;
    fastcgi_param HTTP_AUTHORIZATION $http_authorization;
    fastcgi_pass 127.0.0.1:9000;
}
